### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by kenpeter** [monkeyWangs/doubanMovie#2]
code: https://github.com/kenpeter/myDoubanMovie
visit: http://doubanmov.shopshop.space

error:

```
vue.esm.js:1447 TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at movingList (http://doubanmov.shopshop.space/static/js/app.fb445042ed21485b7632.js:1:4428)
    at t._wrappedGetters.(anonymous function) (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:11:34287)
    at oe.s.(anonymous function) (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:11:32153)
    at yi.get (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:6:53211)
    at yi.evaluate (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:6:54112)
    at oe.movingList (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:6:10552)
    at Object.get [as movingList] (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:11:32221)
    at s.movingList (http://doubanmov.shopshop.space/static/js/app.fb445042ed21485b7632.js:1:9871)
    at yi.get (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:6:53211)
    at yi.evaluate (http://doubanmov.shopshop.space/static/js/vendor.1160383a5c83b579ed2c.js:6:54112)
```

**Comment by muwoo** [comment]
I think you may use ES6 (for in) ? if the array is undefined
